language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository

before_install:
  - chmod +x mvnw

script:
  - ./mvnw test cobertura:cobertura coveralls:report -B -Punit-test
