language: java
jdk: oraclejdk11

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

script:
  - ./mvnw test org.jacoco:jacoco-maven-plugin:report coveralls:report -B -Punit-test